services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.2
    container_name: keycloak
    command: start
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public
      # Optional: Set hostname for Keycloak (useful behind a proxy)
      # KC_HOSTNAME: localhost
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080
    depends_on:
      postgres:
        condition: service_healthy # Wait for PostgreSQL to be ready
    networks:
      - keycloak-net

  postgres:
    image: postgres:17-alpine3.21
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak -d keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  keycloak-net:
    driver: bridge